app:
  name: "qasystem"
  environment: "development"
jwt:
  secret_key: "qasystem"

server:
  port: "8080"

database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: mysql
  dbname: QASystem
  charset: utf8mb4
  parseTime: true
  loc: Local
